FROM continuumio/anaconda3:latest
MAINTAINER "Vladislav Ladenkov <waryak2012@mail.ru>"

WORKDIR /

COPY src/algo ./src/algo
COPY config.yml ./src/algo
ENV CONFIG algo/config.yml

WORKDIR /src

ENTRYPOINT ["python3", "-m", "algo.main"]


